name: previous
on: push
# Prevent writing to the repository using the CI token.
# Ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions: read-all
env:
  MAKEFLAGS: "-j 2"
jobs:
  test-previous:
    runs-on:
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-exp-runner-tool-cache-50gb
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-gha-demo-buf
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"
      - name: Setup Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.cache/buf/${{ runner.os }}/x86_64/bin
            ~/.cache/buf/${{ runner.os }}/x86_64/go/pkg/mod
            ~/.cache/buf/${{ runner.os }}/x86_64/gocache
            ~/.cache/buf/${{ runner.os }}/x86_64/include
            ~/.cache/buf/${{ runner.os }}/x86_64/versions
      - name: make-test
        run: make test
